export const paths = {
  home: "/",
  shop: "/shop",
  login: "/login",
  cashier: "/cashier",
  driver: "/driver",
  admin: "/admin",
  adminMenu: "/admin/menu",
  adminStaff: "/admin/staff",
  adminStaffEdit: "/admin/staff/edit",
  adminStaffHistory: "/admin/staff/history",
  adminHistory: "/admin/history",
  adminSalesHistory: "/admin/sales-history",
  adminCompare: "/admin/compare",
  adminProducts: "/admin/products",
  adminBundles: "/admin/bundles",
  adminOrders: "/admin/orders",
  adminFlagged: "/admin/flagged",
  adminZones: "/admin/zones",
  adminReports: "/admin/reports",
  adminAudit: "/admin/audit",
  adminDrivers: "/admin/drivers",
  adminRate: "/admin/rate",
  adminSettings: "/admin/settings",
} as const;
