// Generated by build/gen_react.py from docs/u2gas-all-screens.html.
// Do not edit: correct the gallery and re-run the generator.
// Screen: DIVIDER — USER APP  node 1:2271  app CUSTOMER
import * as A from "../assets";

export const node = "1:2271";
export const height = 1739;
export const html = `<div style="position:absolute;inset:0;background:#000"></div><p data-node="1:2272" style="position:absolute;left:-271.0px;top:595px;width:1012px;font-family:&quot;Barlow Condensed&quot;,&quot;Arial Narrow&quot;,sans-serif;font-weight:600;font-size:300px;line-height:400px;letter-spacing:0;color:#ffffff;white-space:nowrap;transform:rotate(90deg)">USER APP</p>`;
