// Generated by build/gen_react.py from docs/u2gas-all-screens.html.
// Do not edit: correct the gallery and re-run the generator.
// Screen: DIVIDER — CASHIER APP  node 1:4680  app CASHIER
import * as A from "../assets";

export const node = "1:4680";
export const height = 1739;
export const html = `<div style="position:absolute;inset:0;background:#000"></div><p data-node="1:4681" style="position:absolute;left:-437.5px;top:595px;width:1345px;font-family:&quot;Barlow Condensed&quot;,&quot;Arial Narrow&quot;,sans-serif;font-weight:600;font-size:300px;line-height:400px;letter-spacing:0;color:#ffffff;white-space:nowrap;transform:rotate(90deg)">CASHIER APP</p>`;
