// Generated by build/gen_react.py from docs/u2gas-all-screens.html.
// Do not edit: correct the gallery and re-run the generator.
// Screen: DIVIDER — DRIVER APP  node 1:4984  app DRIVER
import * as A from "../assets";

export const node = "1:4984";
export const height = 1739;
export const html = `<p data-node="1:4985" style="position:absolute;left:-394.0px;top:690px;width:1228px;font-size:300px;line-height:210px;letter-spacing:-12px;color:#1317e4;white-space:nowrap;transform:rotate(90deg)">DRIVER APP</p><p style="position:absolute;left:20px;bottom:20px;font-size:11px;color:rgba(0,0,0,.35);letter-spacing:-0.44px;line-height:1.7">Layer is named &ldquo;DRIVER DRIVER DRIVER DRIVER&rdquo;<br>on all four dividers, whatever it reads.</p>`;
