// Generated by build/gen_react.py from docs/u2gas-all-screens.html.
// Do not edit: correct the gallery and re-run the generator.
// Screen: Frame 125  node 1:581  app CUSTOMER
import * as A from "../assets";

export const node = "1:581";
export const height = 266;
export const html = `<span class="asset-img" data-node="1:582" aria-hidden="true" style="--src:url('${A.a7}');position:absolute;left:0;top:0;width:266px;height:266px;object-fit:contain"></span>`;
