// Generated by build/gen_react.py from docs/u2gas-all-screens.html.
// Do not edit: correct the gallery and re-run the generator.
// Screen: Frame 124  node 1:500  app CUSTOMER
import * as A from "../assets";

export const node = "1:500";
export const height = 266;
export const html = `<span class="asset-img" data-node="1:501" aria-hidden="true" style="--src:url('${A.a6}');position:absolute;left:0;top:0;width:266px;height:266px;object-fit:contain"></span><p style="position:absolute;left:8px;bottom:6px;font-size:9px;color:rgba(0,0,0,.45);letter-spacing:-0.36px;line-height:1.6">layer: TWO TONE THUMBS UP 2</p>`;
