// Generated by build/gen_react.py from docs/u2gas-all-screens.html.
// Do not edit: correct the gallery and re-run the generator.

//
// Every artboard in the supplied gallery, as the markup the screens use, so
// the product and the reference cannot drift apart.

import * as DividerDriverApp from "./screens/DividerDriverApp";
import * as Home1_2274 from "./screens/Home1_2274";
import * as Notifs from "./screens/Notifs";
import * as DriverScanSuccessful from "./screens/DriverScanSuccessful";
import * as DriverScanFailed from "./screens/DriverScanFailed";
import * as DeliveryNotifs from "./screens/DeliveryNotifs";
import * as DriverProfile from "./screens/DriverProfile";
import * as CompletedDelivery from "./screens/CompletedDelivery";
import * as DividerCashierApp from "./screens/DividerCashierApp";
import * as Home1_4437 from "./screens/Home1_4437";
import * as ScanSuccessful from "./screens/ScanSuccessful";
import * as ScanFail from "./screens/ScanFail";
import * as WalkInInput from "./screens/WalkInInput";
import * as WalkInPayment from "./screens/WalkInPayment";
import * as WalkInPayment2 from "./screens/WalkInPayment2";
import * as WalkInPayConfirm from "./screens/WalkInPayConfirm";
import * as NotifsState1 from "./screens/NotifsState1";
import * as NotifsState2 from "./screens/NotifsState2";
import * as NotifsState1Expanded from "./screens/NotifsState1Expanded";
import * as StaffProfile from "./screens/StaffProfile";
import * as AdminStockNotificationExpanded from "./screens/AdminStockNotificationExpanded";
import * as DividerAdminApp from "./screens/DividerAdminApp";
import * as HomeBlueprint from "./screens/HomeBlueprint";
import * as Dashboard from "./screens/Dashboard";
import * as StaffLayout1 from "./screens/StaffLayout1";
import * as StaffLayout2 from "./screens/StaffLayout2";
import * as AddStaff from "./screens/AddStaff";
import * as StaffLayout2Details from "./screens/StaffLayout2Details";
import * as StaffHistoryDriver1 from "./screens/StaffHistoryDriver1";
import * as StaffHistoryDriver2 from "./screens/StaffHistoryDriver2";
import * as GasHistory from "./screens/GasHistory";
import * as UpdateGas from "./screens/UpdateGas";
import * as GasLvlCheck from "./screens/GasLvlCheck";
import * as NotifState1 from "./screens/NotifState1";
import * as NotifState2 from "./screens/NotifState2";
import * as DividerUserApp from "./screens/DividerUserApp";
import * as Home from "./screens/Home";
import * as InsufficientGasInput from "./screens/InsufficientGasInput";
import * as PayWalkIn from "./screens/PayWalkIn";
import * as PayDelivery from "./screens/PayDelivery";
import * as OrderSummary from "./screens/OrderSummary";
import * as PaymentSuccessful from "./screens/PaymentSuccessful";
import * as PaymentFailed from "./screens/PaymentFailed";
import * as ReceiptPrinting from "./screens/ReceiptPrinting";
import * as ReceiptDisplay from "./screens/ReceiptDisplay";
import * as ReceiptDisplayAlt from "./screens/ReceiptDisplayAlt";
import * as Frame124 from "./screens/Frame124";
import * as LogIn1 from "./screens/LogIn1";
import * as Frame125 from "./screens/Frame125";
import * as LogIn2 from "./screens/LogIn2";
import * as TransHistory from "./screens/TransHistory";
import * as ShopSearch from "./screens/ShopSearch";
import * as ShopSingleItem from "./screens/ShopSingleItem";
import * as ShopItemUnavailable from "./screens/ShopItemUnavailable";
import * as CartItemUnavailable from "./screens/CartItemUnavailable";
import * as CartEmpty from "./screens/CartEmpty";
import * as CheckoutWalkIn from "./screens/CheckoutWalkIn";
import * as CheckoutDelivery from "./screens/CheckoutDelivery";
import * as CheckoutNoDeliveryAddress from "./screens/CheckoutNoDeliveryAddress";
import * as BlackConcept from "./screens/BlackConcept";
import * as UserProfile from "./screens/UserProfile";
import * as PersonalDts from "./screens/PersonalDts";
import * as PersonalDts2 from "./screens/PersonalDts2";

export interface FigmaArtboard {
  name: string;
  node: string;
  app: string;
  height: number;
  html: string;
}

export const artboards: Record<string, FigmaArtboard> = {
  "1:4984": { name: "DIVIDER — DRIVER APP", node: "1:4984", app: "DRIVER", height: 1739, html: DividerDriverApp.html },
  "1:2274": { name: "HOME", node: "1:2274", app: "DRIVER", height: 1739, html: Home1_2274.html },
  "88:55": { name: "notifs", node: "88:55", app: "DRIVER", height: 50, html: Notifs.html },
  "1:4908": { name: "DRIVER SCAN SUCCESSFUL", node: "1:4908", app: "DRIVER", height: 1739, html: DriverScanSuccessful.html },
  "1:4938": { name: "DRIVER SCAN FAILED", node: "1:4938", app: "DRIVER", height: 1739, html: DriverScanFailed.html },
  "1:4683": { name: "DELIVERY NOTIFS", node: "1:4683", app: "DRIVER", height: 1739, html: DeliveryNotifs.html },
  "1:4968": { name: "DRIVER PROFILE", node: "1:4968", app: "DRIVER", height: 956, html: DriverProfile.html },
  "1:4803": { name: "COMPLETED DELIVERY", node: "1:4803", app: "DRIVER", height: 1739, html: CompletedDelivery.html },
  "1:4680": { name: "DIVIDER — CASHIER APP", node: "1:4680", app: "CASHIER", height: 1739, html: DividerCashierApp.html },
  "1:4437": { name: "HOME", node: "1:4437", app: "CASHIER", height: 1739, html: Home1_4437.html },
  "1:4377": { name: "SCAN SUCCESSFUL", node: "1:4377", app: "CASHIER", height: 1739, html: ScanSuccessful.html },
  "1:4407": { name: "SCAN FAIL", node: "1:4407", app: "CASHIER", height: 1739, html: ScanFail.html },
  "1:4466": { name: "WALK-IN INPUT", node: "1:4466", app: "CASHIER", height: 1739, html: WalkInInput.html },
  "1:4592": { name: "WALK-IN PAYMENT", node: "1:4592", app: "CASHIER", height: 1739, html: WalkInPayment.html },
  "1:4047": { name: "WALK-IN PAYMENT 2", node: "1:4047", app: "CASHIER", height: 1739, html: WalkInPayment2.html },
  "1:4527": { name: "WALK-IN PAY CONFIRM", node: "1:4527", app: "CASHIER", height: 1739, html: WalkInPayConfirm.html },
  "1:4114": { name: "NOTIFS STATE 1", node: "1:4114", app: "CASHIER", height: 1711, html: NotifsState1.html },
  "1:4192": { name: "NOTIFS STATE 2", node: "1:4192", app: "CASHIER", height: 1711, html: NotifsState2.html },
  "1:4285": { name: "NOTIFS STATE 1 (EXPANDED)", node: "1:4285", app: "CASHIER", height: 1711, html: NotifsState1Expanded.html },
  "1:4665": { name: "STAFF PROFILE", node: "1:4665", app: "CASHIER", height: 1711, html: StaffProfile.html },
  "83:246": { name: "Admin stock notification expanded", node: "83:246", app: "CASHIER", height: 1739, html: AdminStockNotificationExpanded.html },
  "1:4044": { name: "DIVIDER — ADMIN APP", node: "1:4044", app: "ADMIN", height: 1739, html: DividerAdminApp.html },
  "1:2299": { name: "HOME BLUEPRINT", node: "1:2299", app: "ADMIN", height: 1924, html: HomeBlueprint.html },
  "1:2454": { name: "DASHBOARD", node: "1:2454", app: "ADMIN", height: 1924, html: Dashboard.html },
  "1:2624": { name: "STAFF LAYOUT 1", node: "1:2624", app: "ADMIN", height: 1924, html: StaffLayout1.html },
  "1:2747": { name: "STAFF LAYOUT 2", node: "1:2747", app: "ADMIN", height: 1924, html: StaffLayout2.html },
  "1:2686": { name: "ADD STAFF", node: "1:2686", app: "ADMIN", height: 1924, html: AddStaff.html },
  "1:2803": { name: "STAFF LAYOUT 2 DETAILS", node: "1:2803", app: "ADMIN", height: 1441, html: StaffLayout2Details.html },
  "1:3675": { name: "STAFF HISTORY - DRIVER (1)", node: "1:3675", app: "ADMIN", height: 1739, html: StaffHistoryDriver1.html },
  "1:3781": { name: "STAFF HISTORY - DRIVER (2)", node: "1:3781", app: "ADMIN", height: 1739, html: StaffHistoryDriver2.html },
  "1:2847": { name: "GAS HISTORY", node: "1:2847", app: "ADMIN", height: 1924, html: GasHistory.html },
  "1:3075": { name: "UPDATE GAS", node: "1:3075", app: "ADMIN", height: 1924, html: UpdateGas.html },
  "1:3887": { name: "GAS LVL CHECK", node: "1:3887", app: "ADMIN", height: 1739, html: GasLvlCheck.html },
  "1:3245": { name: "NOTIF STATE 1", node: "1:3245", app: "ADMIN", height: 1739, html: NotifState1.html },
  "1:3461": { name: "NOTIF STATE 2", node: "1:3461", app: "ADMIN", height: 1739, html: NotifState2.html },
  "1:2271": { name: "DIVIDER — USER APP", node: "1:2271", app: "CUSTOMER", height: 1739, html: DividerUserApp.html },
  "1:251": { name: "HOME", node: "1:251", app: "CUSTOMER", height: 1739, html: Home.html },
  "1:175": { name: "INSUFFICIENT GAS INPUT", node: "1:175", app: "CUSTOMER", height: 1739, html: InsufficientGasInput.html },
  "1:1344": { name: "PAY - WALK-IN", node: "1:1344", app: "CUSTOMER", height: 1739, html: PayWalkIn.html },
  "1:326": { name: "PAY - DELIVERY", node: "1:326", app: "CUSTOMER", height: 1739, html: PayDelivery.html },
  "1:583": { name: "ORDER SUMMARY", node: "1:583", app: "CUSTOMER", height: 1739, html: OrderSummary.html },
  "1:421": { name: "PAYMENT SUCCESSFUL", node: "1:421", app: "CUSTOMER", height: 1739, html: PaymentSuccessful.html },
  "1:502": { name: "PAYMENT FAILED", node: "1:502", app: "CUSTOMER", height: 1739, html: PaymentFailed.html },
  "1:669": { name: "RECEIPT PRINTING", node: "1:669", app: "CUSTOMER", height: 1739, html: ReceiptPrinting.html },
  "1:762": { name: "RECEIPT DISPLAY", node: "1:762", app: "CUSTOMER", height: 1739, html: ReceiptDisplay.html },
  "1:989": { name: "RECEIPT DISPLAY ALT", node: "1:989", app: "CUSTOMER", height: 1739, html: ReceiptDisplayAlt.html },
  "1:500": { name: "Frame 124", node: "1:500", app: "CUSTOMER", height: 266, html: Frame124.html },
  "1:1219": { name: "LOG IN 1", node: "1:1219", app: "CUSTOMER", height: 956, html: LogIn1.html },
  "1:581": { name: "Frame 125", node: "1:581", app: "CUSTOMER", height: 266, html: Frame125.html },
  "1:1281": { name: "LOG IN 2", node: "1:1281", app: "CUSTOMER", height: 956, html: LogIn2.html },
  "1:2107": { name: "TRANS HISTORY", node: "1:2107", app: "CUSTOMER", height: 2000, html: TransHistory.html },
  "1:1438": { name: "SHOP - SEARCH", node: "1:1438", app: "CUSTOMER", height: 1800, html: ShopSearch.html },
  "1:1462": { name: "SHOP - Single ITEM", node: "1:1462", app: "CUSTOMER", height: 1500, html: ShopSingleItem.html },
  "1:1488": { name: "SHOP - ITEM UNAVAILABLE", node: "1:1488", app: "CUSTOMER", height: 1500, html: ShopItemUnavailable.html },
  "1:1517": { name: "CART - ITEM UNAVAILABLE", node: "1:1517", app: "CUSTOMER", height: 2000, html: CartItemUnavailable.html },
  "1:1624": { name: "CART - EMPTY", node: "1:1624", app: "CUSTOMER", height: 2000, html: CartEmpty.html },
  "1:1703": { name: "CHECKOUT - WALK-IN", node: "1:1703", app: "CUSTOMER", height: 2000, html: CheckoutWalkIn.html },
  "1:1827": { name: "CHECKOUT - DELIVERY", node: "1:1827", app: "CUSTOMER", height: 2000, html: CheckoutDelivery.html },
  "1:1952": { name: "CHECKOUT NO DELIVERY ADDRESS", node: "1:1952", app: "CUSTOMER", height: 2000, html: CheckoutNoDeliveryAddress.html },
  "1:2074": { name: "BLACK CONCEPT", node: "1:2074", app: "CUSTOMER", height: 2000, html: BlackConcept.html },
  "1:2090": { name: "USER PROFILE", node: "1:2090", app: "CUSTOMER", height: 1190, html: UserProfile.html },
  "1:2210": { name: "PERSONAL DTS", node: "1:2210", app: "CUSTOMER", height: 2000, html: PersonalDts.html },
  "1:2244": { name: "PERSONAL DTS 2", node: "1:2244", app: "CUSTOMER", height: 2000, html: PersonalDts2.html },
};

export const byName = (name: string): FigmaArtboard | undefined =>
  Object.values(artboards).find((a) => a.name === name);
