import type {
  UserProfile,
  Product,
  ReceiptItem,
  HistoryReceipt,
  TankHistoryRecord,
  SalesHistoryItem,
  AdminStaffProfile,
  GasHistoryRecord,
  TimeFilter,
  AdminSalesHistoryItem,
  StaffDriverRecord,
  StaffCashierRecord,
  DriverDeliveryOrder,
  CashierTransactionItem,
} from "@/types";

export const dummyUserProfile: UserProfile = {
  firstName: "JOHN",
  lastName: "doe",
  email: "EXAMPLE@GMAIL.COM",
  address: "4, Anthony Villa, Um...",
  avatar: "/images/profile-avatar.png",
};

export const dummyUsers: UserProfile[] = [
  dummyUserProfile,
  {
    firstName: "SARAH",
    lastName: "connor",
    email: "SARAH.C@U2GAS.COM",
    address: "12, Marina Road, Victoria Island, Lagos",
    avatar: "/images/staff-avatar-3.png",
  },
  {
    firstName: "MICHAEL",
    lastName: "drake",
    email: "M.DRAKE@U2GAS.COM",
    address: "7, Airport Road, Ikeja, Lagos",
    avatar: "/images/staff-avatar-3.png",
  },
  {
    firstName: "CHIDINMA",
    lastName: "okafor",
    email: "CHIDI.O@U2GAS.COM",
    address: "24, Awolowo Road, Ikoyi, Lagos",
    avatar: "/images/profile-avatar.png",
  },
];

export const products: Product[] = [
  {
    product_id: "1",
    name: "U2 GAS CYLINDER",
    subtitle: "12.5KG",
    description: "12.5KG",
    image: "/images/image1.png",
    priceNaira: 15000,
    price_kobo: 1500000,
    bgColor: "#E9B90D4D",
    unavailable: false,
    sizeScale: 1.15,
  },
  {
    product_id: "2",
    name: "U2 POWER HOSE",
    subtitle: "6 FEET",
    description: "6 FEET",
    image: "/images/image2.png",
    priceNaira: 11000,
    price_kobo: 1100000,
    bgColor: "#02133033",
    sizeScale: 1.0,
  },
  {
    product_id: "3",
    name: "U2 IGNITION BATTERY",
    subtitle: "6-PACK ENERGIZER",
    description: "6-PACK ENERGIZER",
    image: "/images/image4.png",
    priceNaira: 6000,
    price_kobo: 600000,
    bgColor: "#9C9EEC",
    sizeScale: 1.0,
  },
  {
    product_id: "4",
    name: "U2 HOSE CLAMPS",
    subtitle: "HEAVY DUTY",
    description: "HEAVY DUTY",
    image: "/images/image3.png",
    priceNaira: 4500,
    price_kobo: 450000,
    bgColor: "#B10E0E4D",
    sizeScale: 1.0,
  },
  {
    product_id: "5",
    name: "U2 POWER HOSE",
    subtitle: "8 FEET",
    description: "8 FEET",
    image: "/images/image2.png",
    priceNaira: 14000,
    price_kobo: 1400000,
    bgColor: "#02133033",
    sizeScale: 1.18,
  },
  {
    product_id: "6",
    name: "U2 POWER HOSE",
    subtitle: "4 FEET",
    description: "4 FEET",
    image: "/images/image2.png",
    priceNaira: 8500,
    price_kobo: 850000,
    bgColor: "#02133033",
    sizeScale: 0.84,
  },
  {
    product_id: "7",
    name: "U2 GAS CYLINDER",
    subtitle: "6KG",
    description: "6KG",
    image: "/images/image1.png",
    priceNaira: 12000,
    price_kobo: 1200000,
    bgColor: "#E9B90D4D",
    sizeScale: 0.96,
  },
  {
    product_id: "8",
    name: "U2 GAS CYLINDER",
    subtitle: "3KG",
    description: "3KG",
    image: "/images/image1.png",
    priceNaira: 7500,
    price_kobo: 750000,
    bgColor: "#E9B90D4D",
    sizeScale: 0.8,
  },
  {
    product_id: "9",
    name: "U2 IGNITION BATTERY",
    subtitle: "12-PACK ENERGIZER",
    description: "12-PACK ENERGIZER",
    image: "/images/image4.png",
    priceNaira: 11000,
    price_kobo: 1100000,
    bgColor: "#9C9EEC",
    sizeScale: 1.12,
  },
  {
    product_id: "10",
    name: "U2 IGNITION BATTERY",
    subtitle: "9V ENERGIZER",
    description: "9V ENERGIZER",
    image: "/images/image4.png",
    priceNaira: 4000,
    price_kobo: 400000,
    bgColor: "#9C9EEC",
    sizeScale: 0.86,
  },
  {
    product_id: "11",
    name: "U2 HOSE CLAMPS",
    subtitle: "SET OF 6",
    description: "SET OF 6",
    image: "/images/image3.png",
    priceNaira: 6500,
    price_kobo: 650000,
    bgColor: "#B10E0E4D",
    sizeScale: 1.12,
  },
  {
    product_id: "12",
    name: "U2 HOSE CLAMPS",
    subtitle: "SET OF 3",
    description: "SET OF 3",
    image: "/images/image3.png",
    priceNaira: 3500,
    price_kobo: 350000,
    bgColor: "#B10E0E4D",
    sizeScale: 0.86,
  },
];

export const shopItems: Product[] = products;
export const defaultShopItems: Product[] = products;

export const dummyReceiptItems: ReceiptItem[] = [
  {
    id: "1",
    title: "6-pack Energizer ignition batteries",
    image: "/shop/battery-9v.jpg",
    priceNaira: 10000,
    quantity: 1,
  },
  {
    id: "2",
    title: "6-pack Energizer ignition batteries",
    image: "/shop/battery-9v.jpg",
    priceNaira: 10000,
    quantity: 1,
  },
];

export const dummyReceiptData = {
  orderId: "ORD-89421",
  date: "17 MAR",
  items: dummyReceiptItems,
};

export const HISTORY_MONTHS = [
  "MARCH",
  "APRIL",
  "MAY",
  "JUNE",
  "JULY",
] as const;

export const dummyHistoryReceipts: HistoryReceipt[] = [
  {
    id: "hist-1",
    orderNumber: "[reference num]",
    date: "17 MAR",
    month: "MARCH",
    deliveryStatus: "DELIVERY IN PROGRESS",
    progressStep: 3,
    progressLabel: "In motion",
    paymentMedium: "TRANSFER(BANK TRANS)",
    paymentMediumAmount: 24000,
    entryFee: "0.0",
    entryType: "ONLINE",
    time: "17/03/27, 08:15:34",
    reference: "[reference num]",
    subtotal: 24000,
    deliveryFee: "0.0",
    total: 24000,
    items: [
      {
        id: "item-1",
        title: "LPG",
        subtitle: "( 200.4 L @ 1346/L )",
        image: "/images/image1.png",
        priceNaira: 100000,
      },
      {
        id: "item-2",
        title: "6-Pack Energizer\nignition batteries",
        subtitle: "(2 pieces)",
        image: "/shop/battery-9v.jpg",
        priceNaira: 24000,
      },
    ],
    qrCode: "/images/qr-code.png",
  },
  {
    id: "hist-2",
    orderNumber: "U2#82910-41413",
    date: "17 MAR",
    month: "MARCH",
    deliveryStatus: "DELIVERY IN PROGRESS",
    progressStep: 2,
    progressLabel: "in motion",
    customerName: "MR DAVID JOHNSON (0802...)",
    statusOnline: "ONLINE",
    time: "18:10 (12-03-2023)",
    reference: "U2#82910-41413",
    subtotal: 100000,
    deliveryFee: "FREE",
    total: 100000,
    items: [
      {
        id: "item-3",
        title: "LPG ( 200.4 L @1346/L )",
        image: "/images/image1.png",
        priceNaira: 100000,
      },
    ],
    qrCode: "/images/qr-code.png",
  },
  {
    id: "hist-3",
    orderNumber: "ORD-89350",
    date: "05 APR",
    month: "APRIL",
    deliveryStatus: "DELIVERED",
    progressStep: 4,
    progressLabel: "delivered",
    customerName: "ALEXANDER G.",
    statusOnline: "COMPLETED",
    time: "14:20 (05-04-2023)",
    reference: "U2#82910-41380",
    subtotal: 17500,
    deliveryFee: "FREE",
    total: 17500,
    items: [
      {
        id: "item-4",
        title: "12.5kg Cooking Gas Refill",
        image: "/images/image1.png",
        priceNaira: 17500,
      },
    ],
    qrCode: "/images/qr-code.png",
  },
];

export const dummyTankHistory: TankHistoryRecord[] = [
  {
    id: "REC-9041",
    timestamp: "TODAY, 14:32",
    level: 38,
    type: "MANUAL_UPDATE",
    volumeLiters: 1900,
    operator: "Admin 01",
  },
  {
    id: "REC-9038",
    timestamp: "YESTERDAY, 18:45",
    level: 46,
    type: "DISPENSE",
    volumeLiters: 2300,
    operator: "Cashier Station A",
  },
  {
    id: "REC-9031",
    timestamp: "03 OCT, 09:15",
    level: 72,
    type: "REFILL",
    volumeLiters: 3600,
    operator: "Depot Truck 04",
  },
  {
    id: "REC-9022",
    timestamp: "01 OCT, 11:20",
    level: 85,
    type: "REFILL",
    volumeLiters: 4250,
    operator: "Depot Truck 02",
  },
  {
    id: "REC-9015",
    timestamp: "28 SEP, 16:50",
    level: 22,
    type: "AUDIT",
    volumeLiters: 1100,
    operator: "Safety Inspector",
  },
];

export const mockTankHistory = dummyTankHistory;

export const dummySalesHistory: SalesHistoryItem[] = [
  {
    id: "sale-1",
    type: "LPG",
    method: "POS",
    liters: 5000,
    amount: 5000000,
    timestamp: "14:22",
  },
  {
    id: "sale-2",
    type: "LPG",
    method: "POS",
    liters: 5345,
    amount: 5345000,
    timestamp: "11:05",
  },
];

export interface TabSalesData {
  totalLiters: string;
  items: SalesHistoryItem[];
}

export const salesHistoryByTab: Record<string, TabSalesData> = {
  TODAY: {
    totalLiters: "10.345",
    items: [
      {
        id: "sale-today-1",
        type: "LPG",
        method: "POS",
        liters: 5000,
        amount: 5000000,
        timestamp: "14:22",
      },
      {
        id: "sale-today-2",
        type: "LPG",
        method: "POS",
        liters: 5345,
        amount: 5345000,
        timestamp: "11:05",
      },
    ],
  },
  "THIS MONTH": {
    totalLiters: "248.910",
    items: [
      {
        id: "sale-tm-1",
        type: "LPG",
        method: "POS",
        liters: 62000,
        amount: 62000000,
        timestamp: "05 OCT, 14:10",
      },
      {
        id: "sale-tm-2",
        type: "LPG",
        method: "TRANSFER",
        liters: 84000,
        amount: 84000000,
        timestamp: "03 OCT, 11:30",
      },
      {
        id: "sale-tm-3",
        type: "LPG",
        method: "POS",
        liters: 52910,
        amount: 52910000,
        timestamp: "01 OCT, 16:45",
      },
      {
        id: "sale-tm-4",
        type: "LPG",
        method: "CASH",
        liters: 50000,
        amount: 50000000,
        timestamp: "29 SEP, 09:20",
      },
    ],
  },
  MAY: {
    totalLiters: "185.420",
    items: [
      {
        id: "sale-may-1",
        type: "LPG",
        method: "POS",
        liters: 95000,
        amount: 95000000,
        timestamp: "28 MAY, 15:00",
      },
      {
        id: "sale-may-2",
        type: "LPG",
        method: "POS",
        liters: 90420,
        amount: 90420000,
        timestamp: "14 MAY, 10:15",
      },
    ],
  },
  JUNE: {
    totalLiters: "312.850",
    items: [
      {
        id: "sale-jun-1",
        type: "LPG",
        method: "POS",
        liters: 120000,
        amount: 120000000,
        timestamp: "22 JUN, 16:40",
      },
      {
        id: "sale-jun-2",
        type: "LPG",
        method: "TRANSFER",
        liters: 102850,
        amount: 102850000,
        timestamp: "15 JUN, 12:20",
      },
      {
        id: "sale-jun-3",
        type: "LPG",
        method: "POS",
        liters: 90000,
        amount: 90000000,
        timestamp: "08 JUN, 09:50",
      },
    ],
  },
};

export const dummyAdminStaff: AdminStaffProfile[] = [
  {
    id: "staff-1",
    firstName: "JOHN",
    lastName: "doe",
    role: "EXAMPLE@GMAIL.COM",
    email: "EXAMPLE@GMAIL.COM",
    bankName: "OPAY",
    accountNumber: "9137307797",
    avatarUrl: "/images/profile-avatar.png",
    isOnline: true,
  },
  {
    id: "staff-2",
    firstName: "SARAH",
    lastName: "connor",
    role: "SARAH.C@U2GAS.COM",
    email: "SARAH.C@U2GAS.COM",
    bankName: "KUDA",
    accountNumber: "2019485721",
    avatarUrl: "",
    isBlackPlaceholder: true,
    isOnline: true,
  },
  {
    id: "staff-3",
    firstName: "MICHAEL",
    lastName: "drake",
    role: "M.DRAKE@U2GAS.COM",
    email: "M.DRAKE@U2GAS.COM",
    bankName: "ACCESS",
    accountNumber: "0123984712",
    avatarUrl: "/images/staff-avatar-3.png",
    isOnline: false,
  },
  {
    id: "staff-4",
    firstName: "CHIDINMA",
    lastName: "okafor",
    role: "CHIDI.O@U2GAS.COM",
    email: "CHIDI.O@U2GAS.COM",
    bankName: "ZENITH",
    accountNumber: "2209148301",
    avatarUrl: "/images/profile-avatar.png",
    isOnline: true,
  },
];

export const dummyGasHistory: GasHistoryRecord[] = [
  {
    id: "gas-rec-23-mar-add",
    dayLabel: "23rd",
    amountTons: 2,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "MARCH",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-31-mar-add",
    dayLabel: "31st",
    amountTons: 2,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "MARCH",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-14-mar-add",
    dayLabel: "14th",
    amountTons: 1.5,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "MARCH",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-05-mar-add",
    dayLabel: "5th",
    amountTons: 3,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "MARCH",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-20-mar-rem",
    dayLabel: "20th",
    amountTons: 1,
    actionType: "REMOVAL",
    operatorName: "MR EMEKA",
    month: "MARCH",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-10-mar-rem",
    dayLabel: "10th",
    amountTons: 0.5,
    actionType: "REMOVAL",
    operatorName: "MR EMEKA",
    month: "MARCH",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-18-apr-add",
    dayLabel: "18th",
    amountTons: 2.5,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "APRIL",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-08-apr-add",
    dayLabel: "8th",
    amountTons: 2,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "APRIL",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-15-apr-rem",
    dayLabel: "15th",
    amountTons: 1.2,
    actionType: "REMOVAL",
    operatorName: "MR EMEKA",
    month: "APRIL",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-22-jun-add",
    dayLabel: "22nd",
    amountTons: 3,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "JUNE",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-12-jun-rem",
    dayLabel: "12th",
    amountTons: 1.5,
    actionType: "REMOVAL",
    operatorName: "MR EMEKA",
    month: "JUNE",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-16-may-add",
    dayLabel: "16th",
    amountTons: 2.0,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "MAY",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-24-may-rem",
    dayLabel: "24th",
    amountTons: 1.0,
    actionType: "REMOVAL",
    operatorName: "MR EMEKA",
    month: "MAY",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-09-jul-add",
    dayLabel: "9th",
    amountTons: 2.8,
    actionType: "ADDITION",
    operatorName: "MR GIFT",
    month: "JULY",
    qrCode: "/images/qr-code.png",
  },
  {
    id: "gas-rec-19-jul-rem",
    dayLabel: "19th",
    amountTons: 1.4,
    actionType: "REMOVAL",
    operatorName: "MR EMEKA",
    month: "JULY",
    qrCode: "/images/qr-code.png",
  },
];

export interface AdminTabSalesData {
  totalLiters: string;
  items: AdminSalesHistoryItem[];
}

export const salesDataByTab: Record<TimeFilter, AdminTabSalesData> = {
  TODAY: {
    totalLiters: "10.345",
    items: [
      {
        id: "s-today-1",
        title: "₦23,000 ~ 34.4L",
        date: new Date(2027, 9, 20, 12, 32),
        paymentMethod: "POS",
      },
      {
        id: "s-today-2",
        title: "₦23,000 ~ 34.4L",
        date: new Date(2027, 9, 20, 12, 32),
        paymentMethod: "TRANS",
      },
      {
        id: "s-today-3",
        title: "₦23,000 ~ 34.4L",
        date: new Date(2027, 9, 20, 12, 32),
        paymentMethod: "CASH",
      },
    ],
  },
  "THIS MONTH": {
    totalLiters: "248.910",
    items: [
      {
        id: "s-tm-1",
        title: "₦45,000 ~ 68.2L",
        date: new Date(2027, 9, 18, 15, 10),
        paymentMethod: "POS",
      },
      {
        id: "s-tm-2",
        title: "₦32,500 ~ 49.0L",
        date: new Date(2027, 9, 15, 11, 45),
        paymentMethod: "TRANS",
      },
      {
        id: "s-tm-3",
        title: "₦18,000 ~ 27.1L",
        date: new Date(2027, 9, 12, 9, 20),
        paymentMethod: "CASH",
      },
    ],
  },
  MAY: {
    totalLiters: "185.420",
    items: [
      {
        id: "s-may-1",
        title: "₦28,000 ~ 42.0L",
        date: new Date(2027, 4, 28, 14, 0),
        paymentMethod: "POS",
      },
      {
        id: "s-may-2",
        title: "₦50,000 ~ 75.5L",
        date: new Date(2027, 4, 22, 16, 30),
        paymentMethod: "TRANS",
      },
      {
        id: "s-may-3",
        title: "₦21,000 ~ 31.8L",
        date: new Date(2027, 4, 15, 10, 15),
        paymentMethod: "CASH",
      },
    ],
  },
  JUNE: {
    totalLiters: "192.150",
    items: [
      {
        id: "s-jun-1",
        title: "₦36,000 ~ 54.2L",
        date: new Date(2027, 5, 29, 13, 22),
        paymentMethod: "POS",
      },
      {
        id: "s-jun-2",
        title: "₦41,000 ~ 62.0L",
        date: new Date(2027, 5, 20, 11, 50),
        paymentMethod: "TRANS",
      },
      {
        id: "s-jun-3",
        title: "₦25,000 ~ 37.6L",
        date: new Date(2027, 5, 10, 8, 40),
        paymentMethod: "CASH",
      },
    ],
  },
};

export const dummyStaffDriverRecords: StaffDriverRecord[] = [
  {
    id: "d-1",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
  },
  {
    id: "d-2",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
  },
  {
    id: "d-3",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
  },
];

export const dummyStaffCashierRecords: StaffCashierRecord[] = [
  {
    id: "c-1",
    title: "₦23,000 ~ 34.4L",
    date: new Date(2027, 9, 20, 12, 32),
    paymentMethod: "TRANS",
  },
  {
    id: "c-2",
    title: "₦23,000 ~ 34.4L",
    date: new Date(2027, 9, 20, 12, 32),
    paymentMethod: "POS",
  },
  {
    id: "c-3",
    title: "₦23,000 ~ 34.4L",
    date: new Date(2027, 9, 20, 12, 32),
    paymentMethod: "CASH",
  },
];

export const dummyDriverDeliveryOrders: DriverDeliveryOrder[] = [
  {
    id: "ddo-1",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
    customerName: "AJAINO CALEB",
    mapImage: "/images/map.jpg",
    status: "COMPLETED",
  },
  {
    id: "ddo-2",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
    customerName: "SARAH WILLIAMS",
    mapImage: "/images/map.jpg",
    status: "COMPLETED",
  },
  {
    id: "ddo-3",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
    customerName: "EMMANUEL CHIDI",
    mapImage: "/images/map.jpg",
    status: "COMPLETED",
  },
  {
    id: "ddo-4",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
    customerName: "DAVID OKON",
    mapImage: "/images/map.jpg",
    status: "UNFULFILLED",
  },
  {
    id: "ddo-5",
    title: "12.5 KG @ 1300 ~ 1KG",
    date: new Date(2027, 9, 20, 12, 32),
    customerName: "BLESSING ADAMS",
    mapImage: "/images/map.jpg",
    status: "CANCELLED",
  },
];

export const dummyCashierTransactions: CashierTransactionItem[] = [
  {
    id: "tx-1",
    title: "₦23,000 ~ 34.4L",
    date: new Date(2027, 9, 20, 12, 32),
    paymentMethod: "POS",
    mode: "IN—PERSON",
  },
  {
    id: "tx-2",
    title: "₦23,000 ~ 34.4L",
    date: new Date(2027, 9, 20, 12, 32),
    paymentMethod: "TRANS",
    mode: "IN—PERSON",
  },
  {
    id: "tx-3",
    title: "₦23,000 ~ 34.4L",
    date: new Date(2027, 9, 20, 12, 32),
    paymentMethod: "CASH",
    mode: "IN—PERSON",
  },
  {
    id: "tx-4",
    title: "₦18,500 ~ 27.6L",
    date: new Date(2027, 9, 20, 11, 15),
    paymentMethod: "CASH",
    mode: "IN—PERSON",
  },
  {
    id: "tx-5",
    title: "₦45,000 ~ 67.2L",
    date: new Date(2027, 9, 20, 10, 0),
    paymentMethod: "POS",
    mode: "ONLINE",
  },
  {
    id: "tx-6",
    title: "₦32,000 ~ 47.8L",
    date: new Date(2027, 9, 20, 9, 30),
    paymentMethod: "TRANS",
    mode: "ONLINE",
  },
];


